/* =========================================================
   i18n.js — 中/英双语
   策略：以中文为「key」，路由切换后做 DOM 文本节点遍历替换
   - 全局 window.Lang.t("中文") -> 翻译后字符串
   - Lang.translateDom(rootEl) 翻译节点子树（text nodes + 常见属性）
   - 持久化到 localStorage.viaim_brand_os.lang
   ========================================================= */

const LangDict = {
  // ---- 导航 / Sidebar（中文为默认，此处映射到英文）----
  '主页': 'Home',
  '灵感池': 'Inspiration Pool',
  '品牌源': 'Brand Source',
  '资产库': 'Asset Library',
  '生成工作台': 'Generate Studio',
  '上市规划': 'Launch Plan',
  '甘特排期': 'Gantt',
  '复用图谱': 'Reuse Map',
  '资产清单': 'Assets',
  '界面原型': 'UI Prototype',
  '品牌幻灯片': 'Brand Slides',
  '图像视频音频': 'Image / Video / Audio',
  '硬件提示音': 'Hardware Cues',
  'UX 反馈音': 'UX Feedback',
  '单张模板': 'Single template',
  '多张连排（自动排版）': 'Multi-slide deck (auto-layout)',
  '原型类型': 'Prototype type',
  'device chrome': 'Device chrome',
  '生成 UI': 'Generate UI',
  '生成单张': 'Generate slide',
  '生成多张连排 deck': 'Generate deck',
  '导出 HTML': 'Export HTML',
  '合规': 'Compliance',
  '模板': 'Templates',
  '技能库': 'Skills',
  'API & SDK': 'API & SDK',
  '产物归档': 'Output Archive',
  '设置': 'Settings',
  'PRD 文档': 'PRD Doc',
  '最近': 'RECENT',
  '命令面板': 'Command Palette',
  '尚无产物': 'No outputs yet',
  '工作区': 'Workspace',
  // 灵感池
  '把外部资源（网页、GitHub、工具、文章、片段）放进来。系统抓取 → AI 分析 → 一键合并到 Brand Source 草案。': 'Drop in external sources (web pages, GitHub repos, tools, articles, snippets). The system fetches → AI analyzes → one-click merge into Brand Source draft.',
  '+ 添加资源': '+ Add source',
  'URL · 或粘贴正文片段': 'URL · or paste a snippet',
  '给一句话备注（可选） · 你想用它来做什么': 'One-line note (optional) · how do you want to use it',
  '抓取并入库': 'Fetch & save',
  '取消': 'Cancel',
  '全部': 'All',
  '待处理': 'Inbox',
  '已分析': 'Reviewed',
  '已应用': 'Applied',
  '这里还空空的': 'Nothing here yet',
  '尚未分析': 'Not analyzed',
  '点击右上「分析」让 LLM 生成结构化建议（需配置 LLM API）。': 'Click "Analyze" to have the LLM produce structured recommendations (requires LLM API).',
  '摘要 / SUMMARY': 'SUMMARY',
  '适用段 / TARGET SECTIONS': 'TARGET SECTIONS',
  '关键洞察 / KEY TAKEAWAYS': 'KEY TAKEAWAYS',
  '建议规则 / APPLICABLE RULES': 'APPLICABLE RULES',
  '建议品牌改动 / SUGGESTED PATCHES': 'SUGGESTED PATCHES',
  '段': 'Section',
  '规则': 'Rule',
  '理由': 'Rationale',
  '置信': 'Confidence',
  '→ 合并到 Brand Source 草案': '→ Merge into Brand Source draft',
  '标记为已忽略': 'Mark as ignored',
  '风险与注意': 'Risk & Caveats',
  '已应用于': 'Applied to',
  '查看抓取正文（': 'View fetched content (',
  '尚未渲染': 'Not rendered yet',
  '分析': 'Analyze',
  '重新分析': 'Re-analyze',
  '分析中…': 'Analyzing…',
  '分析完成': 'Analysis complete',
  '已抓取并入库': 'Fetched & saved',
  '已入库（片段）': 'Snippet saved',
  '已合并': 'Merged',
  '已标记为忽略': 'Marked as ignored',
  // 文件上传
  '上传 Markdown / 文本文件 · 支持 .md .markdown .mdx .txt': 'Upload Markdown / text file · .md .markdown .mdx .txt',
  '点击或拖拽文件到此处': 'Click or drop files here',
  '支持多文件 · 单个 ≤ 2MB · 文件名将作为标题': 'Multiple files · ≤ 2MB each · filename becomes title',
  '或': 'or',
  '请填入 URL / 正文 或 上传文件': 'Please fill URL / text or upload a file',
  // Brand Spec viewer
  '已发布的完整品牌规范 · 此为只读视图。要修改请创建新草案。': 'Read-only view of the published brand spec. Create a new draft to edit.',
  '↓ 导出 spec.md': '↓ Export spec.md',
  '+ 基于此版本编辑（创建新 draft）': '+ Edit based on this version (create new draft)',
  '版本': 'Version',
  '发布时间': 'Published at',
  '发布人': 'Published by',
  '变更说明': 'Change note',
  '基于': 'Based on',
  '上一发布版本': 'Previous version',
  'Visual Theme · 视觉氛围': 'Visual Theme',
  'Color Palette · 色板': 'Color Palette',
  'Typography · 字体': 'Typography',
  'Spacing & Grid · 间距与栅格': 'Spacing & Grid',
  'Component Stylings · 组件规范': 'Component Stylings',
  'Motion · 动效': 'Motion',
  'Voice & Tone · 语气': 'Voice & Tone',
  'Brand Marks · 标识规范': 'Brand Marks',
  "Don't · 反例 / 禁止用法": "Don't · Forbidden",
  '字号 scale': 'Size scale',
  '字重': 'Weights',
  '中文排版规则（来自灵感池合并）': 'CN typography rules (from Inspiration Pool)',
  '由 Brand OS 自动生成于': 'Auto-generated by Brand OS at',
  '已创建草案': 'Draft created',
  'spec.md 已下载': 'spec.md downloaded',
  'Markdown 已复制': 'Markdown copied',
  '导出预览 · EXPORT PREVIEW': 'EXPORT PREVIEW',
  '渲染预览': 'Rendered',
  'Markdown 原文': 'Raw Markdown',
  '↓ 下载 .md': '↓ Download .md',
  // §10 Users
  'Users · 用户信息': 'Users · Personas',
  '主/次/反向画像': 'Primary / Secondary / Anti personas',
  '为什么记录用户信息': 'Why record user personas',
  '主画像 · Primary Persona': 'Primary Persona',
  '次画像 · Secondary Personas': 'Secondary Personas',
  '反向画像 · Anti Personas（不针对的用户）': 'Anti Personas (NOT-targeted users)',
  '反向画像 · 不针对的用户': 'Anti Personas · NOT-targeted',
  '+ 添加次画像': '+ Add secondary persona',
  '不针对的用户类型': 'User type NOT to target',
  '原因（与品牌哪点冲突）': 'Why (which brand value conflicts)',
  '身份 / 标签': 'Role / Label',
  '年龄段': 'Age range',
  '一句话画像': 'One-line description',
  '使用场景（每行一条）': 'Use scenes (one per line)',
  '核心需求': 'Core needs',
  '痛点': 'Pain points',
  '价值观': 'Values',
  '使用场景': 'Scenes',
  '尚未配置反向画像': 'No anti-personas configured',
  '未配置主画像': 'No primary persona',
  '忽略': 'Ignored',
  '已选': 'Selected',
  '个文件，点「抓取并入库」提交': ' file(s) · click "Fetch & save" to submit',
  '只支持': 'only supports',
  '超过 2MB': 'exceeds 2MB',
  // 兼容旧版 / 历史 archive 标题中的英文
  'Brand Source': 'Brand Source',
  'Asset Library': 'Asset Library',
  'Generate Studio': 'Generate Studio',
  'Generation Studio': 'Generate Studio',
  'Compliance': 'Compliance',
  'Templates': 'Templates',
  'Output Archive': 'Output Archive',
  'Settings': 'Settings',
  'RECENT': 'RECENT',
  '新建 workspace': 'New workspace',
  '第二品牌': 'Second brand',
  '新增 workspace': 'Add workspace',

  // ---- Topbar ----
  '切换 brand 版本': 'Switch brand version',

  // ---- 通用按钮 ----
  '保存': 'Save',
  '删除': 'Delete',
  '取消': 'Cancel',
  '关闭': 'Close',
  '导出': 'Export',
  '复制': 'Copy',
  '上传': 'Upload',
  '+ 添加': '+ Add',
  '渲染预览': 'Render',
  '测试连接': 'Test',
  '发布 →': 'Publish →',
  '放弃 draft': 'Discard draft',
  '+ 上传资产': '+ Upload asset',
  '+ 上传': '+ Upload',
  '+ 更多': '+ More',
  '导出 PNG': 'Export PNG',
  '导出 JSON': 'Export JSON',
  '清空 Archive': 'Clear archive',
  '查看 lint →': 'View lint →',
  '查看 →': 'View →',
  '点击「生成 Prompt」开始': 'Click "Generate" to start',
  '生成 Prompt': 'Generate prompt',
  '生成 Mini MD': 'Generate brief',
  '生成中…': 'Generating…',
  '下载 .md': 'Download .md',

  // ---- L3 Studio ----
  '场景 / 配置': 'Scene / Config',
  '资产': 'Asset',
  '品牌锁': 'Brand Lock',
  '实时预览': 'Live preview',
  '尚未渲染': 'Not rendered yet',

  // ---- L1 / L2 表单 ----
  '输入': 'Input',
  '场景描述': 'Scene',
  '关键产品 / 资产': 'Product / Asset',
  '媒介 / 平台': 'Medium / Platform',
  '风格调性': 'Mood',
  '不绑定资产': 'No asset',
  '项目信息': 'Project Info',
  '项目名': 'Project name',
  '场景类型': 'Scene type',
  '时长 / 周期': 'Duration',
  '调性': 'Tone',
  '关键产品': 'Key product',
  '交付物': 'Deliverables',
  '本地兜底（未配置 API）': 'Local fallback (no API)',
  'LLM 生成': 'via LLM',

  // ---- Brand Source ----
  '机器可读的品牌 source of truth。修改将进入 draft 状态，发布后创建新版本快照。': 'Machine-readable source of truth. Edits enter draft; publishing creates a new snapshot.',
  '影响分析': 'Impact Analysis',
  '氛围描述（atmosphere）': 'Atmosphere',
  '密度（density）': 'Density',
  '用一两句话描述品牌的视觉氛围，会被注入到所有生成 prompt 中。': 'A short description of the visual atmosphere; injected into every generation prompt.',
  '字号 scale（逗号分隔）': 'Size scale (comma)',
  '字重 weights': 'Weights',
  'base unit (px)': 'Base unit (px)',
  'scale（逗号分隔）': 'Scale (comma)',
  'tone（语气）': 'Tone',
  'Do（应做）': 'Do',
  "Don't（避免）": "Don't",
  '每行一条': 'One per line',
  'wordmark 文字': 'Wordmark text',
  'safe zone ratio': 'Safe-zone ratio',
  '最小高度 (px)': 'Min height (px)',
  '禁止的做法': 'Forbidden practice',
  '原因': 'Reason',
  '尚未配置反例': 'No examples configured',

  // ---- Assets ----
  '所有产品级视觉资产的中央仓库。强制 schema 化打标，避免变垃圾场。': 'Central repository of product visual assets. Required schema tagging keeps it from rotting.',
  '点击或拖拽文件到此处': 'Click or drop files here',
  '支持 PNG / JPG / WebP / SVG · 单个 ≤ 10MB': 'PNG / JPG / WebP / SVG · ≤ 10MB each',
  '所有 product': 'All products',
  '所有 angle': 'All angles',
  '所有 colorway': 'All colorways',
  '所有 scene': 'All scenes',
  '自然语言/标签搜索…': 'Search by tag…',
  '没有资产': 'No assets',
  '尝试更换筛选条件，或点击右上角上传': 'Adjust filters, or upload from the top right',

  // ---- Compliance ----
  'v0.1 必备 5 条 lint 规则（R1-R5）。这是「真规范」与「装饰品」的分水岭。': 'v0.1 ships 5 lint rules (R1-R5). This is the divide between real governance and decoration.',
  '最近 Lint 结果': 'Recent lint results',
  '当前会话无 lint': 'No lint this session',
  '条违规': ' violations',
  'tokens 合规': 'tokens OK',
  'logo 留白': 'logo safe-zone',
  '字体合规': 'typography OK',
  '未检测': 'not checked',
  '导出 ·': 'Export ·',

  // ---- Settings ----
  '所有 API key 仅保存在你的浏览器 localStorage，不会上传到任何服务器。': 'All API keys are stored only in your localStorage and never leave the browser.',
  'LLM API（必填）': 'LLM API (required)',
  'Embedding API（可选）': 'Embedding API (optional)',
  'Image Generation API（可选 · L4）': 'Image Generation API (optional · L4)',
  '行为开关': 'Behavior toggles',
  '危险区': 'Danger zone',
  '恢复出厂设置': 'Factory reset',
  '细调系统行为': 'Fine-tune system behavior',
  '未配置 LLM 时使用本地模板兜底': 'Use local templates as fallback when LLM is not configured',
  '生成后自动归档到 Output Archive': 'Auto-archive every generation',
  'L3 渲染时自动跑 Compliance Lint': 'Run compliance lint on L3 render',
  '一键重置所有数据，包括 Brand 草案、Asset 文件、Archive、Settings。不可撤销。': 'Wipe all data: drafts, assets, archive, settings. Irreversible.',
  '启用 Embedding 搜索': 'Enable embedding search',
  '启用图像生成': 'Enable image generation',
  '用于 L1 Prompt 生成、L2 Mini MD 生成、Command Palette 自然语言意图识别': 'Used for L1 prompt, L2 brief, and ⌘K natural-language intent.',
  '支持任何 OpenAI 兼容协议（DeepSeek / 通义 / Moonshot 等）。': 'Compatible with any OpenAI-protocol provider (DeepSeek / Qwen / Moonshot / etc.)',
  '用于 Asset Library 自然语言搜索。未启用时使用基础 tag 搜索。': 'Used by Asset Library semantic search. Falls back to tag search when disabled.',
  '已配置': 'configured',
  '未配置': 'not configured',
  '已启用': 'enabled',
  '未启用': 'disabled',
  // 兼容旧值
  'configured': 'configured',
  'not configured': 'not configured',
  'enabled': 'enabled',
  'disabled': 'disabled',

  // ---- Archive ----
  '每次生成都自动归档。三态采纳信号（adopted / rejected / iterated）作为后续 fine-tune 的训练信号。': 'Every generation is auto-archived. Three-state adoption (adopted / rejected / iterated) becomes future fine-tune signal.',
  '采纳信号': 'Adoption',

  // ---- Templates ----
  'v0.1 内置 3 个高频模板（社交卡 / 文档封面 / 活动 banner）。Phase 2 扩展到 8-10 个。模板用 HTML/SVG 渲染，避开 diffusion 不稳定性。': 'v0.1 ships 3 high-frequency templates (social card / doc cover / banner). Phase 2 extends to 8-10. Rendered via HTML/SVG to avoid diffusion instability.',
  '未来扩展（Phase 2）': 'Future (Phase 2)',

  // ---- API ----
  'PRD §5.7 对内输出层。所有写操作走 API，UI 是 client。Vitana 等下游消费方接入零成本。': 'PRD §5.7 internal output layer. All writes go through the API, UI is the client. Zero-cost integration for downstream consumers like Vitana.',
  '当前状态': 'Status',
  'v0.1 端点': 'v0.1 Endpoints',
  '本地 client（当前页面正在用）': 'Local client (used by this page)',
  'SDK（Phase 2）': 'SDK (Phase 2)',
  '→ Settings 配置 key': '→ Settings · configure',

  // ---- Home ----
  '欢迎回到 Brand OS': 'Welcome back to Brand OS',
  '这是 viaim 的品牌操作系统。从这里开始管理品牌源、产品资产、生成产物。': 'viaim Brand OS · manage brand source, assets, and outputs from here.',
  '当前 Brand 版本': 'Current brand version',
  '快速开始': 'Quick start',
  '三步上手 Brand OS': 'Three steps to get started',
  '编辑 Brand Source →': 'Edit Brand Source →',
  '查看 Archive': 'View Archive',
  '开始生成 →': 'Start generating →',
  '最近产物': 'Recent outputs',
  'LLM API 未配置': 'LLM API not configured',

  // ---- Toast / 通知 ----
  '已保存': 'Saved',
  '已发布': 'Published',
  '已删除': 'Deleted',
  '已复制': 'Copied',
  '已重置，正在刷新…': 'Reset · reloading…',
  '已发布新版本': 'New version published',
  'draft 已放弃': 'Draft discarded',
  '上传完成，请补全打标': 'Uploaded · please complete tagging',
  '连接成功': 'Connection OK',
  '连接失败': 'Connection failed',
  '尚无 lint 记录': 'No lint records yet',
  // DeepSeek / provider 预设
  '↺ 应用预设': '↺ Apply preset',
  // Skills 库 7 类
  '原型': 'Prototype',
  '营销': 'Marketing',
  'Deck': 'Deck',
  '文档': 'Document',
  '图像': 'Image',
  '视频': 'Video',
  '音频': 'Audio',
  '全部': 'All',
  '已实装': 'Active',
  '敬请期待': 'Coming soon',
  '已加载技能：': 'Skill loaded: ',
  '· 字段已预填，可直接生成或继续微调。': ' · fields prefilled · run as-is or adjust.',
  '· 已为该 skill 预填 deliverables 框架。': ' · deliverables scaffolded for this skill.',
  '· prompt 已预填。': ' · prompt prefilled.',
  '基于 ': 'Based on ',
  ' 7 大类输出整合 ': ' · 7 output categories with ',
  ' 个代表 skill。点击 skill → 自动跳转 Studio 对应 L 级别并预填上下文。': ' representative skills. Click any skill → opens the matching Studio L-level with prefilled context.',
  '单页 / 多屏 / 可交互界面草图': 'Single-page / multi-screen / interactive UI sketches',
  '社交 / 海报 / EDM / 落地页': 'Social cards / posters / EDM / landing pages',
  '横向滑动幻灯片 / Pitch / 周报': 'Horizontal-swipe slides / pitch / weekly',
  'PRD / 纪要 / OKR / Runbook': 'PRDs / minutes / OKRs / runbooks',
  'gpt-image-2 / 产品渲染 / 头像 / 信息图': 'gpt-image-2 / product render / portrait / infographic',
  'Seedance / HyperFrames / 脚本 / 分镜': 'Seedance / HyperFrames / scripts / storyboard',
  '播客 / VO / 音乐 brief / 音频广告': 'Podcast / VO / music brief / audio ads',
  '已应用': 'Applied',
  '推荐：': 'Recommended: ',
  '仅保存到 localStorage，不上传任何服务器。': 'Stored only in localStorage; never uploaded.',
  'OpenAI 兼容': 'OpenAI-compatible',
  'DeepSeek': 'DeepSeek',
  'Anthropic Claude': 'Anthropic Claude',
  'DeepSeek 官方 API · 协议与 OpenAI 完全兼容。deepseek-chat 是 V3，deepseek-reasoner 是 R1。': 'Official DeepSeek API · fully OpenAI-compatible. deepseek-chat is V3, deepseek-reasoner is R1.',
  '通用 OpenAI 协议；任何兼容服务（Moonshot / 通义 / Together / Groq）改 endpoint 即用。': 'Generic OpenAI protocol · any compatible service (Moonshot / Qwen / Together / Groq) works by changing the endpoint.',
  'Anthropic Messages API · 协议与 OpenAI 不同。': 'Anthropic Messages API · different protocol from OpenAI.',

  // ---- Misc page text ----
  '当前查看的': 'Currently viewing',
  '已发布': 'Published',
  '点击「生成 Mini MD」生成 design brief。给 agency / 下游 AI 用。': 'Click "Generate Brief" to produce a design brief for agencies / downstream AI.',
  '若未配置 LLM API，将使用本地模板拼装一份高质量 prompt。': 'If no LLM API is configured, a local template assembles a high-quality prompt.',
  'Engineering Prompt': 'Engineering Prompt',
  'brief.md': 'brief.md',
  '导航': 'Navigate',
  '执行': 'Run',

  // ---- L3 slot labels ----
  '主标题': 'Title',
  '副标题': 'Subtitle',
  '尾部标语': 'Tagline',
  '行动召唤': 'CTA',
  '上标': 'Eyebrow',
  '作者署名': 'Author',
  '时间/地点': 'Date / Location',

  // ---- Compliance bar prefix ----
  '当前会话无 lint': 'No lint',
  '查看 lint': 'View lint',
  '关闭': 'Close',

  // ---- Commands palette categories ----
  '跳转 (Go)': 'Navigate (Go)',
  '新建 (New)': 'Create (New)',
  '资产 (Find)': 'Assets (Find)',
  '切换 (Switch)': 'Switch',
  '动作 (Action)': 'Actions',

  // ---- Studio extras ----
  '不绑定资产': 'No asset bound',
  '点击「生成 Mini MD」生成 design brief。给 agency / 下游 AI 用。': 'Click "Generate Brief" to produce a design brief for agencies / downstream AI.',
  '若未配置 LLM API，将使用本地模板拼装一份高质量 prompt。': 'If no LLM API is configured, a local template assembles a high-quality prompt.',
  '点击「生成 Prompt」开始。': 'Click "Generate prompt" to start.',
};

const Lang = {
  current: 'zh',
  load() {
    try { this.current = localStorage.getItem('viaim_brand_os.lang') || 'zh'; } catch { this.current = 'zh'; }
    document.documentElement.setAttribute('lang', this.current === 'en' ? 'en' : 'zh-CN');
  },
  set(lang) {
    this.current = lang === 'en' ? 'en' : 'zh';
    try { localStorage.setItem('viaim_brand_os.lang', this.current); } catch {}
    document.documentElement.setAttribute('lang', this.current === 'en' ? 'en' : 'zh-CN');
  },
  toggle() { this.set(this.current === 'zh' ? 'en' : 'zh'); },
  t(zh) {
    if (this.current === 'zh') return zh;
    if (zh in LangDict) return LangDict[zh];
    return zh;
  },
  // 翻译节点子树（只在 lang=en 时执行）
  translateDom(root) {
    if (this.current !== 'en' || !root) return;
    // 不递归子树的元素（避免翻译用户输入 / 代码 / 嵌入文档）
    const SKIP_CHILDREN = new Set(['SCRIPT', 'STYLE', 'IFRAME', 'CODE', 'PRE', 'TEXTAREA']);
    const walk = (node) => {
      if (!node) return;
      if (node.nodeType === Node.TEXT_NODE) {
        const raw = node.nodeValue;
        if (!raw) return;
        const trimmed = raw.trim();
        if (!trimmed) return;
        if (/^[\x00-\x7F\s]+$/.test(trimmed) && !LangDict[trimmed]) return;
        if (LangDict[trimmed]) {
          node.nodeValue = raw.replace(trimmed, LangDict[trimmed]);
        } else {
          let replaced = raw;
          let changed = false;
          for (const k of Object.keys(LangDict)) {
            if (k.length < 3) continue;
            if (replaced.includes(k)) {
              replaced = replaced.split(k).join(LangDict[k]);
              changed = true;
            }
          }
          if (changed) node.nodeValue = replaced;
        }
        return;
      }
      if (node.nodeType !== Node.ELEMENT_NODE) return;
      // 所有元素的属性都翻译（包括 input / textarea 的 placeholder）
      ['placeholder', 'title', 'aria-label'].forEach((attr) => {
        const v = node.getAttribute && node.getAttribute(attr);
        if (v && LangDict[v.trim()]) node.setAttribute(attr, LangDict[v.trim()]);
      });
      // 但不递归特定元素的子树
      if (SKIP_CHILDREN.has(node.tagName)) return;
      // input 没有 child text content，跳过递归
      if (node.tagName === 'INPUT') return;
      for (let i = 0; i < node.childNodes.length; i++) walk(node.childNodes[i]);
    };
    walk(root);
  },
  // 全页面翻译（topbar + nav + page + bottom bar）
  translateAll() {
    if (this.current !== 'en') return;
    ['#nav', 'main.main', '#complianceBar', '#cmdkPortal'].forEach((sel) => {
      const el = document.querySelector(sel);
      if (el) this.translateDom(el);
    });
  },
};

window.Lang = Lang;
window.t = (zh) => Lang.t(zh);
